const fs = require('fs');
const path = './src/components/tabs/BroadcastTab.js';
let lines = fs.readFileSync(path, 'utf8').split('\n');
const insertIdx = lines.findIndex(l => l.includes("import VideoPlayer"));
lines.splice(insertIdx + 1, 0, 
  "import BroadcastWarningCard from './Broadcast/BroadcastWarningCard';",
  "import BroadcastStatusBanner from './Broadcast/BroadcastStatusBanner';",
  "import BroadcastServerInfo from './Broadcast/BroadcastServerInfo';",
  "import BroadcastNetworkConfig from './Broadcast/BroadcastNetworkConfig';",
  "import BroadcastSecurityConfig from './Broadcast/BroadcastSecurityConfig';",
  "import BroadcastPlaylistBuilder from './Broadcast/BroadcastPlaylistBuilder';"
);
const startIdx = lines.findIndex(l => l.includes("<View style={styles.warningCard}>"));
lines.splice(startIdx, lines.length - startIdx, 
  "      <BroadcastWarningCard downloadPath={settings.downloadPath} />",
  "",
  "      <BroadcastStatusBanner serverRunning={serverRunning} onToggleServer={handleToggleServer} />",
  "",
  "      {serverRunning && (",
  "        <BroadcastServerInfo localIp={localIp} externalIp={externalIp} port={port} exposeInternetEnabled={exposeInternetEnabled} />",
  "      )}",
  "",
  "      <BroadcastNetworkConfig ",
  "        serverName={serverName} setServerName={setServerName}",
  "        port={port} setPort={setPort}",
  "        dlnaEnabled={dlnaEnabled} setDlnaEnabled={setDlnaEnabled}",
  "        serverRunning={serverRunning}",
  "      />",
  "",
  "      <BroadcastSecurityConfig ",
  "        exposeInternetEnabled={exposeInternetEnabled} setExposeInternetEnabled={setExposeInternetEnabled}",
  "        authEnabled={authEnabled} setAuthEnabled={setAuthEnabled}",
  "        username={username} setUsername={setUsername}",
  "        password={password} setPassword={setPassword}",
  "        serverRunning={serverRunning}",
  "      />",
  "",
  "      <BroadcastPlaylistBuilder ",
  "        history={history} playlist={playlist} setPlaylist={setPlaylist} ",
  "        searchQuery={searchQuery} setSearchQuery={setSearchQuery}",
  "        handleAddToPlaylist={handleAddToPlaylist} handleRemoveFromPlaylist={handleRemoveFromPlaylist} ",
  "        handleMoveUp={handleMoveUp} handleMoveDown={handleMoveDown}",
  "        draggedIndex={draggedIndex} setDraggedIndex={setDraggedIndex} ",
  "        dragOverIndex={dragOverIndex} setDragOverIndex={setDragOverIndex}",
  "        handleDragStart={handleDragStart} handleDragOver={handleDragOver} ",
  "        handleDragLeave={handleDragLeave} handleDrop={handleDrop} handleDragEnd={handleDragEnd}",
  "        handleShuffle={handleShuffle} handleSaveStream={handleSaveStream} ",
  "        handleExportM3u={handleExportM3u} handleImportM3u={handleImportM3u}",
  "        setPreviewVideo={setPreviewVideo} serverRunning={serverRunning} playlistUrl={playlistUrl}",
  "        broadcastLogs={broadcastLogs} clearBroadcastLogs={clearBroadcastLogs}",
  "      />",
  "",
  "      <VideoPlayer ",
  "        visible={!!previewVideo}",
  "        videoPath={previewVideo?.path}",
  "        videoTitle={previewVideo?.title}",
  "        originalItem={previewVideo}",
  "        onClose={() => setPreviewVideo(null)}",
  "      />",
  "    </ScrollView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, overflowY: 'scroll' },",
  "  content: { padding: 32, paddingBottom: 60 },",
  "  header: { marginBottom: 32 },",
  "  title: { fontSize: 32, fontWeight: '700', color: theme.colors.text, marginBottom: 8 },",
  "  subtitle: { fontSize: 16, color: theme.colors.textSecondary, fontStyle: 'italic' }",
  "});"
);
fs.writeFileSync(path, lines.join('\n'));
