import React, { useState } from 'react';
import { View, Image, StyleSheet } from 'react-native';
import { theme } from '../theme';
import logoSrc from '../../public/logo.png';

// logoSrc is a base64 data URI generated by webpack's asset/inline rule.
// This works identically in dev (webpack-dev-server) and packaged builds
// (file:// protocol with no static server).
const FALLBACK_URI = logoSrc;

/**
 * Renders a video thumbnail.
 * Falls back to the SauceBox logo (centered, padded) if no thumbnail URI
 * is provided or if the image fails to load, so cards never break.
 */
export default function VideoThumbnail({ uri, style }) {
  const [useFallback, setUseFallback] = useState(!uri);

  React.useEffect(() => {
    setUseFallback(!uri);
  }, [uri]);

  return (
    <View style={[styles.wrapper, style]}>
      {useFallback ? (
        <View style={[styles.fallback, style]}>
          <Image
            source={{ uri: FALLBACK_URI }}
            style={styles.fallbackImage}
            resizeMode="contain"
          />
        </View>
      ) : (
        <Image
          source={{ uri }}
          style={[styles.fill, style]}
          resizeMode="cover"
          onError={() => setUseFallback(true)}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    overflow: 'hidden',
    backgroundColor: theme.colors.surfaceLight,
  },
  fill: {
    width: '100%',
    height: '100%',
  },
  fallback: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceLight,
  },
  fallbackImage: {
    width: '55%',
    height: '55%',
    opacity: 0.35,
  },
});
