import { StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export const downloadStyles = StyleSheet.create({
  content: {
    padding: 32,
    paddingBottom: 52,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    padding: 36,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 32,
    boxShadow: `0 8px 32px ${theme.colors.border}`,
  },
  inputContainer: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  inputWrapper: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  input: {
    flex: 1,
    backgroundColor: theme.colors.surfaceLight,
    borderRadius: 12,
    padding: 18,
    fontSize: 15,
    color: theme.colors.text,
    borderWidth: 2,
    borderColor: `${theme.colors.primary}30`,
    outlineStyle: 'none',
  },
  inputHint: {
    fontSize: 12,
    color: theme.colors.textTertiary,
    fontStyle: 'italic',
    marginTop: 8,
  },
  downloadButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 36,
    paddingVertical: 18,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 180,
    cursor: 'pointer',
    boxShadow: `0 4px 15px ${theme.colors.primary}40`,
  },
  previewButton: {
    backgroundColor: theme.colors.surfaceLight,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    borderWidth: 2,
    borderColor: `${theme.colors.primary}50`,
  },
  previewButtonText: {
    fontSize: 20,
  },
  downloadButtonDisabled: {
    opacity: 0.5,
  },
  downloadButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
  },
  batchSection: {
    backgroundColor: `${theme.colors.primary}10`,
    borderRadius: 16,
    padding: 24,
    borderWidth: 2,
    borderColor: `${theme.colors.primary}30`,
    borderStyle: 'dashed',
    marginBottom: 24,
  },
  batchInfo: {
    marginBottom: 16,
  },
  batchTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 6,
  },
  batchDesc: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  batchButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    cursor: 'pointer',
  },
  batchButtonIcon: {
    fontSize: 20,
  },
  batchButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginBottom: 32,
    display: 'none',
  },
  bottomCardsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
  },
  tipsCard: {
    flex: 1,
    minWidth: 300,
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 28,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    boxShadow: '0 4px 20px rgba(0,0,0,0.5)',
  },
  tipsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.colors.primary,
    marginBottom: 20,
  },
  tipsList: {
    gap: 12,
  },
  tipItem: {
    flexDirection: 'row',
    gap: 12,
  },
  stepCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: `${theme.colors.primary}20`,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.primary,
    marginTop: 2,
  },
  stepNumber: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  tip: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.textSecondary,
    lineHeight: '22px',
  },
  link: {
    color: theme.colors.primary,
    fontWeight: '700',
    textDecorationLine: 'underline',
    cursor: 'pointer',
  }
});
